/*
-- Query: SELECT * FROM TESIS_USABILIDAD.QS_ARTICULO_ADJUNTO
LIMIT 0, 1000

-- Date: 2015-07-09 14:21
*/
INSERT INTO `QS_ARTICULO_ADJUNTO` (`ID_ARCHIVO_ADJUNTO`,`ARCHIVO`,`DESCRIPCION`,`NOMBRE_ARCHIVO`,`TAMANHO_ARCHIVO`,`TIPO_ARCHIVO`,`ID_ARTICULO`,`ID_TIPO_ADJUNTO`) VALUES (2,?,NULL,'9788466657341.jpg',331998,'image/jpeg',2,NULL);
INSERT INTO `QS_ARTICULO_ADJUNTO` (`ID_ARCHIVO_ADJUNTO`,`ARCHIVO`,`DESCRIPCION`,`NOMBRE_ARCHIVO`,`TAMANHO_ARCHIVO`,`TIPO_ARCHIVO`,`ID_ARTICULO`,`ID_TIPO_ADJUNTO`) VALUES (3,?,NULL,'2571870.jpg',52671,'image/jpeg',3,NULL);
INSERT INTO `QS_ARTICULO_ADJUNTO` (`ID_ARCHIVO_ADJUNTO`,`ARCHIVO`,`DESCRIPCION`,`NOMBRE_ARCHIVO`,`TAMANHO_ARCHIVO`,`TIPO_ARCHIVO`,`ID_ARTICULO`,`ID_TIPO_ADJUNTO`) VALUES (5,?,NULL,'nc15.png',104606,'image/png',5,NULL);
INSERT INTO `QS_ARTICULO_ADJUNTO` (`ID_ARCHIVO_ADJUNTO`,`ARCHIVO`,`DESCRIPCION`,`NOMBRE_ARCHIVO`,`TAMANHO_ARCHIVO`,`TIPO_ARCHIVO`,`ID_ARTICULO`,`ID_TIPO_ADJUNTO`) VALUES (6,?,NULL,'nc16.png',73477,'image/png',5,NULL);
INSERT INTO `QS_ARTICULO_ADJUNTO` (`ID_ARCHIVO_ADJUNTO`,`ARCHIVO`,`DESCRIPCION`,`NOMBRE_ARCHIVO`,`TAMANHO_ARCHIVO`,`TIPO_ARCHIVO`,`ID_ARTICULO`,`ID_TIPO_ADJUNTO`) VALUES (7,?,NULL,'nc17.png',31089,'image/png',5,NULL);
INSERT INTO `QS_ARTICULO_ADJUNTO` (`ID_ARCHIVO_ADJUNTO`,`ARCHIVO`,`DESCRIPCION`,`NOMBRE_ARCHIVO`,`TAMANHO_ARCHIVO`,`TIPO_ARCHIVO`,`ID_ARTICULO`,`ID_TIPO_ADJUNTO`) VALUES (8,?,NULL,'9788483260630.jpg',231359,'image/jpeg',6,NULL);
INSERT INTO `QS_ARTICULO_ADJUNTO` (`ID_ARCHIVO_ADJUNTO`,`ARCHIVO`,`DESCRIPCION`,`NOMBRE_ARCHIVO`,`TAMANHO_ARCHIVO`,`TIPO_ARCHIVO`,`ID_ARTICULO`,`ID_TIPO_ADJUNTO`) VALUES (9,?,NULL,'9789587573039.jpg',1344356,'image/jpeg',7,NULL);
INSERT INTO `QS_ARTICULO_ADJUNTO` (`ID_ARCHIVO_ADJUNTO`,`ARCHIVO`,`DESCRIPCION`,`NOMBRE_ARCHIVO`,`TAMANHO_ARCHIVO`,`TIPO_ARCHIVO`,`ID_ARTICULO`,`ID_TIPO_ADJUNTO`) VALUES (11,?,NULL,'9788401015588.jpg',139139,'image/jpeg',1,NULL);
INSERT INTO `QS_ARTICULO_ADJUNTO` (`ID_ARCHIVO_ADJUNTO`,`ARCHIVO`,`DESCRIPCION`,`NOMBRE_ARCHIVO`,`TAMANHO_ARCHIVO`,`TIPO_ARCHIVO`,`ID_ARTICULO`,`ID_TIPO_ADJUNTO`) VALUES (12,?,NULL,'2030460.jpg',56986,'image/jpeg',4,NULL);
