Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('ARY Macedonia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Afganistán', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Albania', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Alemania', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Andorra', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Angola', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Anguilla', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Antigua y Barbuda', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Antillas Holandesas', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Antártida', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Arabia Saudí', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Argelia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Argentina', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Armenia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Aruba', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Australia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Austria', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Azerbaiyán', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Bahamas', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Bahréin', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Bangladesh', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Barbados', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Belice', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Benin', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Bermudas', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Bhután', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Bielorrusia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Bolivia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Bosnia y Herzegovina', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Botsuana', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Brasil', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Brunéi', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Bulgaria', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Burkina Faso', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Burundi', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Bélgica', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Cabo Verde', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Camboya', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Camerún', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Canadá', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Chad', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Chile', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('China', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Chipre', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Ciudad del Vaticano', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Colombia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Comoras', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Congo', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Corea del Norte', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Corea del Sur', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Costa Rica', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Costa de Marfil', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Croacia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Cuba', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Dinamarca', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Dominica', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Ecuador', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Egipto', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('El Salvador', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Emiratos Árabes Unidos', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Eritrea', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Eslovaquia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Eslovenia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('España', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Estados Unidos', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Estonia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Etiopía', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Filipinas', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Finlandia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Fiyi', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Francia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Gabón', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Gambia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Georgia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Ghana', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Gibraltar', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Granada', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Grecia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Groenlandia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Guadalupe', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Guam', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Guatemala', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Guayana Francesa', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Guinea', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Guinea Ecuatorial', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Guinea-Bissau', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Guyana', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Haití', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Honduras', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Hong Kong', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Hungría', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('India', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Indonesia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Iraq', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Irlanda', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Irán', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Isla Bouvet', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Isla Norfolk', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Isla de Navidad', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islandia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islas Caimán', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islas Cocos', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islas Cook', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islas Feroe', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islas Georgias del Sur y Sandwich del Sur', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islas Gland', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islas Heard y McDonald', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islas Malvinas', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islas Marianas del Norte', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islas Marshall', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islas Pitcairn', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islas Salomón', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islas Turcas y Caicos', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islas Vírgenes Británicas', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islas Vírgenes de los Estados Unidos', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Islas ultramarinas de Estados Unidos', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Israel', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Italia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Jamaica', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Japón', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Jordania', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Kazajstán', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Kenia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Kirguistán', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Kiribati', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Kuwait', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Laos', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Lesotho', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Letonia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Liberia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Libia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Liechtenstein', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Lituania', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Luxemburgo', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Líbano', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Macao', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Madagascar', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Malasia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Malawi', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Maldivas', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Malta', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Malí', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Marruecos', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Martinica', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Mauricio', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Mauritania', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Mayotte', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Micronesia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Moldavia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Mongolia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Montserrat', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Mozambique', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Myanmar', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('México', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Mónaco', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Namibia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Nauru', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Nepal', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Nicaragua', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Nigeria', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Niue', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Noruega', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Nueva Caledonia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Nueva Zelanda', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Níger', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Omán', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Pakistán', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Palau', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Palestina', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Panamá', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Papúa Nueva Guinea', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Paraguay', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Países Bajos', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Perú', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Polinesia Francesa', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Polonia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Portugal', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Puerto Rico', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Qatar', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Reino Unido', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('República Centroafricana', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('República Checa', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('República Democrática del Congo', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('República Dominicana', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Reunión', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Ruanda', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Rumania', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Rusia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Sahara Occidental', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Samoa', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Samoa Americana', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('San Cristóbal y Nevis', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('San Marino', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('San Pedro y Miquelón', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('San Vicente y las Granadinas', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Santa Helena', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Santa Lucía', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Santo Tomé y Príncipe', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Senegal', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Serbia y Montenegro', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Seychelles', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Sierra Leona', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Singapur', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Siria', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Somalia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Sri Lanka', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Suazilandia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Sudáfrica', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Sudán', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Suecia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Suiza', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Surinam', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Svalbard y Jan Mayen', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Tailandia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Taiwán', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Tanzania', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Tayikistán', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Territorio Británico del Océano Índico', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Territorios Australes Franceses', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Timor Oriental', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Togo', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Tokelau', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Tonga', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Trinidad y Tobago', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Turkmenistán', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Turquía', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Tuvalu', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Túnez', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Ucrania', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Uganda', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Uruguay', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Uzbekistán', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Vanuatu', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Venezuela', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Vietnam', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Wallis y Futuna', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Yemen', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Yibuti', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Zambia', 2);
Insert into SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_TIPO) values ('Zimbabue', 2);
