INSERT INTO PERMISO_ROL (FECHA_ASIGNACION, HABILITADO, ID_PERMISO, ID_ROL) 
	VALUES ('2015-06-16', NULL, 4, 4);
INSERT INTO PERMISO_ROL (FECHA_ASIGNACION, HABILITADO, ID_PERMISO, ID_ROL) 
	VALUES ('2015-06-16', NULL, 5, 4);
INSERT INTO PERMISO_ROL (FECHA_ASIGNACION, HABILITADO, ID_PERMISO, ID_ROL) 
	VALUES ('2015-06-16', NULL, 4, 1);
INSERT INTO PERMISO_ROL (FECHA_ASIGNACION, HABILITADO, ID_PERMISO, ID_ROL) 
	VALUES ('2015-06-16', NULL, 5, 1);
INSERT INTO PERMISO_ROL (FECHA_ASIGNACION, HABILITADO, ID_PERMISO, ID_ROL) 
	VALUES ('2015-06-16', NULL, 1, 1);
INSERT INTO PERMISO_ROL (FECHA_ASIGNACION, HABILITADO, ID_PERMISO, ID_ROL) 
	VALUES ('2015-06-16', NULL, 2, 1);
INSERT INTO PERMISO_ROL (FECHA_ASIGNACION, HABILITADO, ID_PERMISO, ID_ROL) 
	VALUES ('2015-06-16', NULL, 3, 1);
INSERT INTO PERMISO_ROL (FECHA_ASIGNACION, HABILITADO, ID_PERMISO, ID_ROL) 
	VALUES ('2015-06-16', NULL, 7, 1);
INSERT INTO PERMISO_ROL (FECHA_ASIGNACION, HABILITADO, ID_PERMISO, ID_ROL) 
	VALUES ('2015-06-16', NULL, 6, 1);
INSERT INTO PERMISO_ROL (FECHA_ASIGNACION, HABILITADO, ID_PERMISO, ID_ROL) 
	VALUES ('2015-06-16', NULL, 8, 1);

