INSERT INTO ROL (DESCRIPCION_ROL) 
	VALUES ('ADMINISTRADOR');
INSERT INTO ROL (DESCRIPCION_ROL) 
	VALUES ('SE-CLIENTE');
INSERT INTO ROL (DESCRIPCION_ROL) 
	VALUES ('SE-ADMINISTRADOR');
INSERT INTO ROL (DESCRIPCION_ROL) 
	VALUES ('SUPERVISOR');

