INSERT INTO SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_SUB_TIPO_ANTERIOR, ID_TIPO) 
	VALUES ('ELECTRONICA', NULL, 1);
INSERT INTO SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_SUB_TIPO_ANTERIOR, ID_TIPO) 
	VALUES ('ELECTRODOMESTICOS', NULL, 1);
INSERT INTO SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_SUB_TIPO_ANTERIOR, ID_TIPO) 
	VALUES ('HOGAR', NULL, 1);
INSERT INTO SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_SUB_TIPO_ANTERIOR, ID_TIPO) 
	VALUES ('BELLEZA', NULL, 1);
INSERT INTO SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_SUB_TIPO_ANTERIOR, ID_TIPO) 
	VALUES ('PERFUMES', NULL, 1);
INSERT INTO SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_SUB_TIPO_ANTERIOR, ID_TIPO) 
	VALUES ('SALUD', NULL, 1);
INSERT INTO SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_SUB_TIPO_ANTERIOR, ID_TIPO) 
	VALUES ('DEPORTES', NULL, 1);
INSERT INTO SUB_TIPO (DESCRIPCION_SUB_TIPO, ID_SUB_TIPO_ANTERIOR, ID_TIPO) 
	VALUES ('INFORMATICA', NULL, 1);