INSERT INTO TIPO (ID_TIPO, DESCRIPCION_TIPO) 
	VALUES (1, 'TIPO CATEGORIA_ARTICULO');
INSERT INTO TIPO (ID_TIPO, DESCRIPCION_TIPO) 
	VALUES (2, 'PAIS');
INSERT INTO TIPO (ID_TIPO, DESCRIPCION_TIPO) 
	VALUES (3, 'ACTIVIDAD');
INSERT INTO TIPO (ID_TIPO, DESCRIPCION_TIPO) 
	VALUES (4, 'IDIOMAS');

