INSERT INTO USUARIO (APELLIDOS, CONTRASENHA, CUENTA, ACTIVO, ID_SET_PREFERENCES, LOGIN_EXTERNO, NOMBRES, ID_ROL, ID_SUB_ROL, ID_DATOS_USUARIO) 
	VALUES ('Ferreira A', '$2a$12$k5N7tffcLRg.Gxvf95x9ZOq9jPeaTLlS.Xq2Yip./ELcFo3AYb3.C', 'jm', 1, 0, 1, 'Juan Marcelo', 1, NULL, NULL);
INSERT INTO USUARIO (APELLIDOS, CONTRASENHA, CUENTA, ACTIVO, ID_SET_PREFERENCES, LOGIN_EXTERNO, NOMBRES, ID_ROL, ID_SUB_ROL, ID_DATOS_USUARIO) 
	VALUES ('1', '$2a$12$d4xQlt2PDJ5gZ.mIGJZBRugJm0Gw6lN4wxOuwhaunCXQLP/xJcYzG', 'super', 1, NULL, 0, 'Supervisor', 4, NULL, NULL);

